apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform components
  sourceRepos:
    - https://github.com/SBordier44/eks-devsecops-lab-gitops
    - https://kubernetes.github.io/ingress-nginx
    - https://charts.jetstack.io
    - https://charts.external-secrets.io
    - https://kyverno.github.io/kyverno
  destinations:
    - namespace: ingress-nginx
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: external-secrets
      server: https://kubernetes.default.svc
    - namespace: kyverno
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
