apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-app-secret
  namespace: demo-app-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: demo-app-secret
    creationPolicy: Owner
  data:
    - secretKey: DEMO_MESSAGE
      remoteRef:
        key: eks-devsecops-lab/dev/demo-app
        property: DEMO_MESSAGE
