apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-app-dev

resources:
- namespace.yaml
- ../../base
- ingress.yaml

images:
- name: eks-devsecops-lab-dev-app
  newName: ghcr.io/sbordier44/eks-devsecops-lab-dev-app
  newTag: sha-4cdb056

labels:
- pairs:
    app.kubernetes.io/environment: dev
