apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  template:
    spec:
      containers:
        - name: demo-app
          env:
            - name: DEMO_MESSAGE
              valueFrom:
                secretKeyRef:
                  name: demo-app-config
                  key: DEMO_MESSAGE
