---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-app-config
  namespace: demo-app-dev
spec:
  encryptedData:
    DEMO_MESSAGE: AgB4xl8h1grFcD8smhfQmiTtcuNn6wfOTrcrIrHB+Smhfd6yXD6dfieL3+e8jpwamuhu582ahF9jzxxWsdaArNXeVHPTDvB9qe7Et35+V4wOL/sGx6xRDJ+B/wB5E2Pg5l/ZpdhqC2M2482xKuZhLARZzYQxH2oe61HOgsMynnwit0w4KCBNo18hlhMcg6QEAFvfmWgEPVcTjtbl0oLJXHDyWvPo5M1r0mb5FmYeXCjO7+ztSaNTNwf+GFz3PHVitlhzkWsf1kyJpftYtpcuN2z4X1g2tJxeWUd55TTZ0k+rNu4+MJZYJaKNc91GONcoSWBX4yp7vS0gTvoSQQz29EH55ykzuYJvbpnFC4DnOtPi82LA985GOAMeVhyorTgdsXDt0Ux1+GeuXqsaQ5DnvTZzaQ9eC7Hk6T8y53RY7TP/zWRbJfSvMz/EnEDiUTN8SgGynpTRE+WKelSndgtTTCLoVQXHEhFQVoFFSBDA6FqZyD5OOUjPGLM9WYOWMJneSB//RQmGjwK6CyZpyuIY7K4d02cQ37Vl2LM10yJMrHb1xAW2T5wNRag0XQNJXN4rDoSwfturzpQO/C/rCVbQPVSlEkWLSlmpmw4xJWO45eESoNh4w8SWUBxmb4HWrbxkQ7P1NY0we1+ZTaFivZs5Z1fv7eq5Jo5AiTA2BlM0n+T35OboOfkq9rJxI0MRMu61Kz4k0bPWugeXNK+j8j83RjzTG1p+qTSycJ9L
  template:
    metadata:
      name: demo-app-config
      namespace: demo-app-dev
    type: Opaque
