apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - projects/platform-project.yaml
  - projects/apps-project.yaml
  - applicationsets/apps-applicationset.yaml
  - ../platform/ingress-nginx/dev/app.yaml
  - ../platform/cert-manager/dev/app.yaml
  - ../platform/external-secrets/dev/app.yaml
  - ../platform/kyverno/dev/app.yaml
  - ../platform/kyverno/policies/disallow-latest-tag.yaml
