apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - projects/platform-project.yaml
  - projects/apps-project.yaml
  - applicationsets/apps-applicationset.yaml
  - platform/ingress-nginx.yaml
  - platform/cert-manager.yaml
  - platform/external-secrets.yaml
  - platform/kyverno.yaml
  - policies/disallow-latest-tag.yaml
