apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - projects/apps-project.yaml
  - applications/traefik.yaml
  - applications/cert-manager.yaml
  - resources/cert-manager/clusterissuer-letsencrypt-staging.yaml
  - resources/cert-manager/clusterissuer-letsencrypt-prod.yaml
  - applications/kyverno.yaml
  - applications/kyverno-policies.yaml
  - applications/demo-app-k3s-dev.yaml
