apiVersion: v1
kind: Service
metadata:
  name: demo-app
  labels:
    app.kubernetes.io/name: demo-app
    app.kubernetes.io/part-of: eks-devsecops-lab
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: demo-app
  ports:
    - port: 80
      name: http
      targetPort: http
      protocol: TCP
