apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - policies/require-container-resources-demo-app.yaml
  - policies/require-container-securitycontext-demo-app.yaml
  - policies/verify-signed-demo-app-image.yaml
