apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/SBordier44/eks-devsecops-lab-gitops
              revision: main
              directories:
                - path: apps/*
          - git:
              repoURL: https://github.com/SBordier44/eks-devsecops-lab-gitops
              revision: main
              files:
                - path: clusters/*/config.yaml
  template:
    metadata:
      name: '{{path.basename}}-{{env}}'
      annotations:
        argocd.argoproj.io/sync-wave: "100"
    spec:
      project: apps
      source:
        repoURL: https://github.com/SBordier44/eks-devsecops-lab-gitops
        targetRevision: main
        path: '{{path}}/overlays/{{env}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}-{{namespaceSuffix}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
